---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: config-service-httpproxy
spec:
  virtualhost:
    fqdn: cs.tkg.markalston.net
  routes:
  - conditions:
    - prefix: /
    services:
    - name: dev-config-service
      port: 80