apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 4
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  template:
    spec:
      containers:
      - name: config-service
        securityContext:
          allowPrivilegeEscalation: false
