apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

patchesStrategicMerge:
- service.yaml
- deployment.yaml
- httpproxy.yaml

namespace: config-service

commonLabels:
  version: "1001"

images:
- digest: sha256:3cb09182d307cd22bc652e74bb677ba2791fbef60f5aa8e6604ad4b65d1e089a
  name: azltandevacr.azurecr.io/config-service
  newName: harbor.everi.com/production/config-service

secretGenerator:
- name: registry-secret
  type: docker-registry
  literals:
  - docker-server=DOCKER_REGISTRY_SERVER
  - docker-username=DOCKER_USER
  - docker-password=DOCKER_PASSWORD
  - docker-email=DOCKER_EMAIL
  options:
    disableNameSuffixHash: true
- name: machineKey
  behavior: replace
  envs:
  - decryptionKey.env
  - validationKey.env
- name: image-pull-secret
  files:
    - .dockerconfigjson=/tmp/config.json
  type: kubernetes.io/dockerconfigjson
  options:
    disableNameSuffixHash: true
